-- ============================================================
-- SNOWBRIX E-COMMERCE PLATFORM
-- Operational Monitoring Queries
-- ============================================================
-- Run these to monitor cost, performance, and usage.
-- Used in Module 6 (Operations) and the Streamlit dashboard.
-- ============================================================

USE ROLE ACCOUNTADMIN;  -- ACCOUNT_USAGE requires ACCOUNTADMIN
USE WAREHOUSE REPORTING_WH;

-- ============================================================
-- 1. CREDIT CONSUMPTION BY WAREHOUSE (Last 30 Days)
-- ============================================================

SELECT
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 2) AS TOTAL_CREDITS,
    ROUND(SUM(CREDITS_USED) * 3, 2) AS ESTIMATED_COST_USD,
    COUNT(DISTINCT DATE_TRUNC('day', START_TIME)) AS ACTIVE_DAYS,
    ROUND(SUM(CREDITS_USED) / NULLIF(COUNT(DISTINCT DATE_TRUNC('day', START_TIME)), 0), 2) AS AVG_CREDITS_PER_DAY
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME
ORDER BY TOTAL_CREDITS DESC;

-- ============================================================
-- 2. TOP 20 MOST EXPENSIVE QUERIES (Last 7 Days)
-- ============================================================

SELECT
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    DATABASE_NAME,
    QUERY_TYPE,
    ROUND(TOTAL_ELAPSED_TIME / 1000, 2) AS DURATION_SECONDS,
    ROUND(CREDITS_USED_CLOUD_SERVICES, 4) AS CLOUD_CREDITS,
    BYTES_SCANNED,
    ROUND(BYTES_SCANNED / POWER(1024, 3), 2) AS GB_SCANNED,
    ROWS_PRODUCED,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROUND(PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL, 0) * 100, 1) AS PCT_PARTITIONS_SCANNED,
    LEFT(QUERY_TEXT, 200) AS QUERY_PREVIEW
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND TOTAL_ELAPSED_TIME > 0
ORDER BY TOTAL_ELAPSED_TIME DESC
LIMIT 20;

-- ============================================================
-- 3. WAREHOUSE UTILIZATION HEATMAP (Hourly, Last 7 Days)
-- ============================================================

SELECT
    WAREHOUSE_NAME,
    DATE_TRUNC('hour', START_TIME) AS HOUR,
    ROUND(SUM(CREDITS_USED), 4) AS CREDITS,
    COUNT(*) AS QUERY_COUNT
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME, DATE_TRUNC('hour', START_TIME)
ORDER BY WAREHOUSE_NAME, HOUR;

-- ============================================================
-- 4. QUERIES SCANNING >80% OF PARTITIONS (Inefficient Queries)
-- ============================================================

SELECT
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    ROUND(TOTAL_ELAPSED_TIME / 1000, 2) AS DURATION_SECONDS,
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    ROUND(PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL, 0) * 100, 1) AS PCT_SCANNED,
    LEFT(QUERY_TEXT, 300) AS QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND PARTITIONS_TOTAL > 100
    AND PARTITIONS_SCANNED / NULLIF(PARTITIONS_TOTAL, 0) > 0.8
ORDER BY PARTITIONS_SCANNED DESC
LIMIT 20;

-- ============================================================
-- 5. STORAGE USAGE BY DATABASE
-- ============================================================

SELECT
    DATABASE_NAME,
    ROUND(AVERAGE_DATABASE_BYTES / POWER(1024, 3), 2) AS AVG_STORAGE_GB,
    ROUND(AVERAGE_FAILSAFE_BYTES / POWER(1024, 3), 2) AS FAILSAFE_GB,
    ROUND((AVERAGE_DATABASE_BYTES + AVERAGE_FAILSAFE_BYTES) / POWER(1024, 3), 2) AS TOTAL_GB,
    ROUND((AVERAGE_DATABASE_BYTES + AVERAGE_FAILSAFE_BYTES) / POWER(1024, 4) * 23, 2) AS EST_MONTHLY_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY
WHERE USAGE_DATE = CURRENT_DATE() - 1
    AND DATABASE_NAME LIKE 'ECOMMERCE%'
ORDER BY TOTAL_GB DESC;

-- ============================================================
-- 6. DAILY CREDIT TREND (Last 30 Days)
-- ============================================================

SELECT
    DATE_TRUNC('day', START_TIME) AS DATE,
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 2) AS CREDITS,
    ROUND(SUM(CREDITS_USED) * 3, 2) AS COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY DATE, WAREHOUSE_NAME
ORDER BY DATE, WAREHOUSE_NAME;

-- ============================================================
-- 7. USER ACTIVITY (Who's running what?)
-- ============================================================

SELECT
    USER_NAME,
    COUNT(*) AS TOTAL_QUERIES,
    ROUND(SUM(TOTAL_ELAPSED_TIME) / 1000 / 60, 1) AS TOTAL_MINUTES,
    ROUND(AVG(TOTAL_ELAPSED_TIME) / 1000, 2) AS AVG_QUERY_SECONDS,
    SUM(BYTES_SCANNED) AS TOTAL_BYTES_SCANNED,
    MAX(START_TIME) AS LAST_QUERY
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY USER_NAME
ORDER BY TOTAL_QUERIES DESC;

-- ============================================================
-- 8. FAILED QUERIES (Last 24 Hours)
-- ============================================================

SELECT
    QUERY_ID,
    USER_NAME,
    ERROR_CODE,
    ERROR_MESSAGE,
    LEFT(QUERY_TEXT, 200) AS QUERY_TEXT,
    START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())
    AND EXECUTION_STATUS = 'FAIL'
ORDER BY START_TIME DESC;
