-- ============================================================
-- SNOWBRIX E-COMMERCE PLATFORM
-- Role-Based Access Control (RBAC) Setup
-- ============================================================
-- Run after snowflake_setup.sql and raw_tables.sql.
-- Creates roles, service accounts, and grants.
-- ============================================================

USE ROLE SECURITYADMIN;

-- ============================================================
-- SECTION 1: ROLE HIERARCHY
-- ============================================================

-- Custom roles
CREATE ROLE IF NOT EXISTS ECOMMERCE_ADMIN;
CREATE ROLE IF NOT EXISTS ECOMMERCE_LOADER;
CREATE ROLE IF NOT EXISTS ECOMMERCE_TRANSFORMER;
CREATE ROLE IF NOT EXISTS ECOMMERCE_ANALYST;

-- Hierarchy: all custom roles -> ECOMMERCE_ADMIN -> SYSADMIN
GRANT ROLE ECOMMERCE_LOADER TO ROLE ECOMMERCE_ADMIN;
GRANT ROLE ECOMMERCE_TRANSFORMER TO ROLE ECOMMERCE_ADMIN;
GRANT ROLE ECOMMERCE_ANALYST TO ROLE ECOMMERCE_ADMIN;
GRANT ROLE ECOMMERCE_ADMIN TO ROLE SYSADMIN;


-- ============================================================
-- SECTION 2: LOADER GRANTS (ingestion scripts)
-- ============================================================

-- Database access
GRANT USAGE ON DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_LOADER;

-- Schema access
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_LOADER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_LOADER;

-- Table access (read + write to RAW only)
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_LOADER;
GRANT SELECT, INSERT, UPDATE ON FUTURE TABLES IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_LOADER;

-- Stage access (for file loading)
GRANT READ, WRITE ON ALL STAGES IN SCHEMA ECOMMERCE_RAW.CSV_UPLOADS TO ROLE ECOMMERCE_LOADER;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA ECOMMERCE_RAW.POSTGRES TO ROLE ECOMMERCE_LOADER;

-- Warehouse access
GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE ECOMMERCE_LOADER;


-- ============================================================
-- SECTION 3: TRANSFORMER GRANTS (dbt service account)
-- ============================================================

-- Read from RAW
GRANT USAGE ON DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN DATABASE ECOMMERCE_RAW TO ROLE ECOMMERCE_TRANSFORMER;

-- Write to STAGING
GRANT USAGE ON DATABASE ECOMMERCE_STAGING TO ROLE ECOMMERCE_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE ECOMMERCE_STAGING TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON ALL TABLES IN DATABASE ECOMMERCE_STAGING TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN DATABASE ECOMMERCE_STAGING TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON ALL VIEWS IN DATABASE ECOMMERCE_STAGING TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS IN DATABASE ECOMMERCE_STAGING TO ROLE ECOMMERCE_TRANSFORMER;

-- Write to ANALYTICS
GRANT USAGE ON DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON ALL SCHEMAS IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON ALL TABLES IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON ALL VIEWS IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;
GRANT ALL ON FUTURE VIEWS IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_TRANSFORMER;

-- Warehouse access
GRANT USAGE ON WAREHOUSE TRANSFORMING_WH TO ROLE ECOMMERCE_TRANSFORMER;


-- ============================================================
-- SECTION 4: ANALYST GRANTS (dashboards + ad-hoc)
-- ============================================================

-- Read from ANALYTICS only (no RAW, no STAGING)
GRANT USAGE ON DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON ALL TABLES IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON ALL VIEWS IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN DATABASE ECOMMERCE_ANALYTICS TO ROLE ECOMMERCE_ANALYST;

-- Warehouse access
GRANT USAGE ON WAREHOUSE REPORTING_WH TO ROLE ECOMMERCE_ANALYST;


-- ============================================================
-- SECTION 5: SERVICE ACCOUNTS
-- ============================================================
-- NOTE: In production, use key-pair authentication.
-- Passwords here are for the video demo only.

CREATE USER IF NOT EXISTS SVC_ECOMMERCE_LOADER
    PASSWORD = 'LoaderP@ssw0rd2026!'
    DEFAULT_ROLE = ECOMMERCE_LOADER
    DEFAULT_WAREHOUSE = LOADING_WH
    DEFAULT_NAMESPACE = 'ECOMMERCE_RAW.POSTGRES'
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service account for data ingestion pipelines';
GRANT ROLE ECOMMERCE_LOADER TO USER SVC_ECOMMERCE_LOADER;

CREATE USER IF NOT EXISTS SVC_ECOMMERCE_DBT
    PASSWORD = 'DbtP@ssw0rd2026!'
    DEFAULT_ROLE = ECOMMERCE_TRANSFORMER
    DEFAULT_WAREHOUSE = TRANSFORMING_WH
    DEFAULT_NAMESPACE = 'ECOMMERCE_ANALYTICS.MARTS'
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service account for dbt transformation runs';
GRANT ROLE ECOMMERCE_TRANSFORMER TO USER SVC_ECOMMERCE_DBT;

CREATE USER IF NOT EXISTS SVC_ECOMMERCE_DASHBOARD
    PASSWORD = 'DashP@ssw0rd2026!'
    DEFAULT_ROLE = ECOMMERCE_ANALYST
    DEFAULT_WAREHOUSE = REPORTING_WH
    DEFAULT_NAMESPACE = 'ECOMMERCE_ANALYTICS.MARTS'
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service account for Streamlit dashboard';
GRANT ROLE ECOMMERCE_ANALYST TO USER SVC_ECOMMERCE_DASHBOARD;


-- ============================================================
-- VERIFICATION
-- ============================================================

-- Test LOADER isolation (should succeed)
USE ROLE ECOMMERCE_LOADER;
USE WAREHOUSE LOADING_WH;
SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE();

-- Test LOADER cannot read ANALYTICS (should fail)
-- SELECT * FROM ECOMMERCE_ANALYTICS.MARTS.FCT_ORDERS LIMIT 1;
-- Expected: SQL access control error

-- Test ANALYST isolation (should succeed)
USE ROLE ECOMMERCE_ANALYST;
USE WAREHOUSE REPORTING_WH;
SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE();

-- Test ANALYST cannot read RAW (should fail)
-- SELECT * FROM ECOMMERCE_RAW.POSTGRES.RAW_ORDERS LIMIT 1;
-- Expected: SQL access control error

-- Reset to admin
USE ROLE SYSADMIN;
